### PR TITLE
Use Open Terms Archive user agent across fetcher implementations

### PR DESCRIPTION
**Pull request by MattiSG**
Considering the lack of current problems on the HTML fetcher with no user agent at all, I doubt this would make things worse 🙂

### CODE REVIEW

**Comment by MattiSG** [comment]
This is a suggestion for #814, I probably won't have the time to make this go all the way to the end properly. @Ndpnt feel free to re-implement it however you see fit if you agree with the intention 🙂

**Comment by martinratinaud** [comment]
> Considering the lack of current problems on the HTML fetcher with no user agent at all, I doubt this would make things worse 🙂

What makes you say that?

I remember putting this in because
- I had problem on a document (but did not document it, sorry about that)
- this is common best practices -> https://www.blog.datahut.co/post/web-scraping-best-practices-tips

**Review by martinratinaud — CHANGES_REQUESTED** [review]
Let's discuss this then

**Comment by Ndpnt** [comment]
See https://github.com/ambanum/OpenTermsArchive/issues/805#issuecomment-1082793637

**Review by martinratinaud — APPROVED** [review]
As discussed, I'm fine with that

**Comment by Ndpnt** [comment]
Could we close this PR @MattiSG?

**Comment by Ndpnt** [comment]
It's a long lived PR…

**Comment by MattiSG** [comment]
Okay.

**Pull request closed without merging**
