### PR TITLE
Net Worth?

### PR DESCRIPTION
**Pull request by fixvrvnxadm**
SAMUEL MAN BARFIELD III, NET WORTH?

### CODE REVIEW

**Comment by fixvrvnxadm** [comment]
SAMUEL MAN BARFIELD III, NETWORTH?

**Comment by martinratinaud** [comment]
@clementbiron, any idea who @fixvrvnxadm is :-) and what's this PR is about

Thanks

**Comment by clementbiron** [comment]
@martinratinaud no idea, do we close this PR ?

**Comment by martinratinaud** [comment]
Yes

**Pull request closed without merging**
