### PR TITLE
Add pga ops and config

### PR DESCRIPTION
**Pull request by clementbiron**

### CODE REVIEW

**Comment by afisher3578** [comment]
Hi @clementbiron 

I do not have the ip address yet. I am meeting with the university network center tomorrow to get that setup.

I apologize for the long wait, people I had to meet with were away for holiday this past week.

I will get the ip address to you as soon as possible.

**Comment by afisher3578** [comment]
Hi @clementbiron 

Our server's ip address is:

10.103.43.113

Thanks,
Alex

**Comment by MattiSG** [comment]
Thanks @afisher3578! As discussed over email, this is a private IP address and it cannot be used for deployment. Please keep us updated 🙂

**Review by MattiSG — APPROVED** [review]
I checked the IDs and links, everything seems good on the config side 👍

**Review by MattiSG — COMMENTED** [review]
Looks good to me, but I won't have time to check that properly before Thursday. Could maybe @martinratinaud or @Ndpnt handle deployment?

**Comment by afisher3578** [comment]
Hi @Ndpnt I just added the ssh key to the authorized_keys file so it should work now.

**Pull request merged**
