### PR TITLE
Create Orange Money France.json

### PR DESCRIPTION
**Pull request by dbertho**

### CODE REVIEW

**Comment by clementbiron** [comment]
Thank you for your proposal 👍

Unfortunately we currently only track documents in English but we plan to implement the possibility to track documents in several languages soon.

**Comment by martinratinaud** [comment]
@clementbiron I just checked with @Ndpnt and he told me we should accept french documents.
His POV is that handling several
- countries
- languages

per CGUs will be difficult and should not be underestimated. Maybe we should first accept contributions and figure it out later.

**Comment by clementbiron** [comment]
I share his point of view, this should not be underestimated. But I am afraid that accepting documents in other languages as they are in OTA adds complexity and manual sorting later on.

**Comment by MattiSG** [comment]
Thanks @dbertho for your contribution!
Following #708, in order to ensure the sustainability of Open Terms Archive, the maintenance of service declarations is distributed among actors and are not declared in this repository anymore 🙂
Thanks to our partnership with UFC-Que Choisir, we will soon start tracking specifically French services in https://github.com/OpenTermsArchive/declarations-france/. I thus migrated your PR there by importing your commit. We'll see if the `declarations-france` maintainers are excited about Orange Money too and willing to maintain it over time! 😃

**Pull request closed without merging**
