### PR TITLE
Automatically create an issue in Github when a document is not available anymore

### PR DESCRIPTION
**Pull request by martinratinaud**

### CODE REVIEW

**Comment by MattiSG** [comment]
I would personally be very worried that the repo gets inundated with issues for production stuff that cannot be resolved by anyone through code, only by people who have access to ops, making contribution very hard.

**Comment by martinratinaud** [comment]
@MattiSG 
maybe it's not clear enough but the issues that will be raised after this PR is merged are only if content scraped is not accessible anymore.

So any issue opened through this would be one for fixing a failing service, which is, IMO, what we need to keep the database as updated as possible.

**Comment by martinratinaud** [comment]
I renamed the PR which was not good at all and will put extra attention in the naming of PRs.
I feel a bit alone but need to remember that it's by having clear PRs and issues that we might gain some more contributors.
Thanks!

**Review by clementbiron — APPROVED** [review]
LGTM

**Comment by martinratinaud** [comment]
Thanks for the clarification.

I believe this way of keeping track of issues has already benefited to the team as it helped us keeping real track of what's failing (aka issues)

I understand notifications is the big problem and unfortunately, I checked but there is no such feature today as to be notified only for specific tags on github (feature requests exists here though https://github.community/t/feature-request-subscribe-to-notifications-for-specific-labels-github-issues/1606/10)

- for PRs, what do you suggest? Please note that we are 2 developers here working on this. Should we not do PRs at all?
- I have the opposite vision :-) I feel it's good to see a project is living and that I could contribute easily and rapidly. Also it shows how badly we need support. This, of course, is valid if issues are closed often (which we try to do every week).
- I propose we switch these to the "Discussions" tab and this way you can only be notified about stuff in discussions and not in issues. 
 
I believe this would be the way to go as the terms used (issues/discussions) should be used for their named purpose.

I will move what appears like discussions to me to the discussions tab. Please feel free to turn on notifications only for this @MattiSG. And @LVerneyPEReN also as I saw you liked Matti's comment.

Thanks for the help
@clementbiron FYI

**Comment by MattiSG** [comment]
Based on this issue as well as https://github.com/ambanum/OpenTermsArchive/issues/294#issuecomment-908298263 or https://github.com/ambanum/OpenTermsArchive-api/issues/36, I understand that I mostly had a misunderstanding on what is the process for contribution and decision-making 🙂 I had understood that the aim was to build a common governance, but it is now clear that this is a team working publicly, which is great too.

Thank you for having clarified what is the scope of the team 🙂

**Pull request merged**
