### PR TITLE
Fix missing whitespace on decathlon service declaration

### PR DESCRIPTION
**Pull request by martinratinaud**
Fixes https://github.com/ambanum/OpenTermsArchive/issues/836

In order to test it

in `config/development` put 

```
"services": {
    "declarationsPath": "../france-declarations/declarations"
  },
```

Do `npm i` and launch

```
npm start Decathon
```

The versions created in `data/versions` should have correct whitespaces

### CODE REVIEW

**Comment by martinratinaud** [comment]
@Ndpnt As pdf parsing has changed, I had to change the tests too.

Applying this will result in many new versions created I believe, but I think we have no choice.

**Comment by Ndpnt** [comment]
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@accordproject/markdown-common@0.15.2',
npm WARN EBADENGINE   required: { node: '>=15', npm: '>=6' },
npm WARN EBADENGINE   current: { node: 'v14.18.0', npm: '8.9.0' }
npm WARN EBADENGINE }
```

Currently we use node v14 on production, modify ops to upgrade to last stable version.

**Comment by martinratinaud** [comment]
Good catch, I have node 16 on my laptop.

Updated! @Ndpnt. Although I have a new machine with ansible error so I could not try on vagrant

**Comment by Ndpnt** [comment]
Tested on my vagrant.

**Review by Ndpnt — APPROVED** [review]

**Pull request merged**
